# This image is awesome!
FROM ubuntu
# ARG allows us to set a variable at build time
# The argument has to be passed during build using --build-arg argument
# like: docker build --build-arg curl_bin="curl=7.81.0" -t my-image
# build will not fail when --build-arg is missing!
ARG curl_bin=curl
COPY . /app
RUN apt -y update && apt -y install curl
CMD [ "--argument" ]
# sets linux or windows user to be used for RUN commands and/or containers
# can be overridden with docker run --user
USER newuser
# WORKDIR sets a working directory for RUN commands and / or containers
# can use WORKDIR multiple times 
# the last workdir will be used by containers
WORKDIR
ENTRYPOINT [ "/app/app.sh" ]

# documents ports that containers created from image should expose
EXPOSE 8080
